### ISSUE TITLE
Timer handler

### ISSUE THREAD

**Issue by dodo124** [beegee-tokyo/RUI3-LowPower-Example#1]
Hello and thank you for this code.
However I wonder if I can call the timer in any other rakwireless code, like this one:
https://docs.rakwireless.com/Product-Categories/WisBlock/RAK12034/Quickstart/
Because I want a timer to be called every 20 mi.
The "usual" Timer1 library did not work, probably because it's actually a stm32  doing the job. But I don't think I can use regular cube IDE commands as well.

Any suggestions?

Kind regards Dom

**Comment by beegee-tokyo** [comment]
For sure you can adapt it to use the RAK12034.
Why do you say "Timer1 library did not work", can you give more details? Why do you need to call the timer every 20 milliseconds (I guess that's what you mean with "20 mi")?

**Comment by dodo124** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Hello Bernd,
TimerOne is a arduino library (https://www.arduino.cc/reference/en/libraries/timerone/) at my first try it did not work at all, if it should work I will analyse it further.
20mi means every 20 Minutes. That is becuase of the use case. In short: if the interrupt is not triggered within 20 minutes it should be triggerd by the timer externally.
Kind regards Dominik

Bernd Giesecke schrieb am 22.08.2023 03:07 (GMT +02:00):

For sure you can adapt it to use the RAK12034.Why do you say "Timer1 library did not work", can you give more details? Why do you need to call the timer every 20 milliseconds (I guess that's what you mean with "20 mi")?

**Comment by beegee-tokyo** [comment]
Why do you want to use a timer library when RUI3 has already a timer function?

Just setup the timer with a callback function as shown in our [documentation](https://docs.rakwireless.com/RUI3/System/#timer)

**Comment by dodo124** [comment]
You are right but at the beginning I did not think about the Rui3 functions. I will use the implemented functions of course 😊

Btw. Do you know how to flash the 3172 directly with the STM link? The reference tells me to use the pins. Do this mean directly, like soldering to the pins , or is there a break out?

Kind regards Dominik 

Am 22. August 2023 07:09:02 MESZ schrieb Bernd Giesecke ***@***.***>:

**Comment by beegee-tokyo** [comment]
I don't have the STM Link. I am using sometimes the STM32CubeProgrammer but using the UART port of the RAK3172.
But usually I am using a JLink adapter:
![RAK3172-JLink](https://github.com/beegee-tokyo/RUI3-LowPower-Example/assets/512690/1a2fe1ad-07e1-4ea7-b2bb-b1db110be017)

I guess the connections to a STM Link adapter are similar, but I have no connection diagram for it.

**Comment by dodo124** [comment]
html,body{background-color:#fff;color:#333;line-height:1.4;font-family:sans-serif,Arial,Verdana,Trebuchet MS;}Ahh Ok this was my fault because I actually ment the RAK3372, which is obvisouly using the RAK 3172 and already has breakout pins at P1:

.So now I am going to try out the timer for Rui3 :-)
Bernd Giesecke schrieb am 22.08.2023 08:47 (GMT +02:00):

I don't have the STM Link. I am using sometimes the STM32CubeProgrammer but using the UART port of the RAK3172.But usually I am using a JLink adapter:
I guess the connections to a STM Link adapter are similar, but I have no connection diagram for it.

**Comment by dodo124** [comment]
I got it working. Thanks.
